alias: 开启灯光时调整到变量设定的目标值
description: ""
triggers:
  - entity_id:
    - light.lemesh_cn_1124092164_wy0c24_s_2_light
    - light.lemesh_cn_1120649848_wy0c24_s_2_light
    - light.lemesh_cn_1120805227_wy0c24_s_2_light
    - light.lemesh_cn_1121166528_wy0c24_s_2_light
    - light.lemesh_cn_1121167017_wy0c24_s_2_light
    - light.lemesh_cn_1121167159_wy0c24_s_2_light
    - light.lemesh_cn_1121168146_wy0c24_s_2_light
    - light.opple_cn_831953828_moat_s_2_light
    - light.opple_cn_845038404_moat_s_2_light
    - light.lemesh_cn_1120498967_wy0c24_s_2_light
    - light.lemesh_cn_1120804999_wy0c24_s_2_light
    - light.lemesh_cn_1121162556_wy0c24_s_2_light
    - light.ftd_cn_1125537084_dsplmp_s_2_light
    - light.xiaomi_cn_819688679_lyj3xs_s_3_light
    - light.xiaomi_cn_819783851_lyj3xs_s_3_light
    - light.lemesh_cn_1120561054_wy0c24_s_2_light
    - light.lemesh_cn_1121173938_wy0c24_s_2_light
    - light.lemesh_cn_1123300235_wy0c24_s_2_light
    - light.lemesh_cn_1120805171_wy0c24_s_2_light
    - light.opple_cn_845028809_moat_s_2_light
    - light.opple_cn_847058390_moat_s_2_light
    - light.lemesh_cn_1121162570_wy0c24_s_2_light
    - light.lemesh_cn_1121174323_wy0c24_s_2_light
    - light.aupu_cn_822711474_s10m2_s_2_light
    - light.lemesh_cn_1120804698_wy0c24_s_2_light
    - light.lemesh_cn_1120985233_wy0c24_s_2_light
    - light.aupu_cn_822614309_s10m2_s_2_light
    - light.ftd_cn_1119497471_dsplmp_s_2_light
    - light.ftd_cn_1120477125_dsplmp_s_2_light
    - light.yeelink_cn_112632203_lamp1_s_2_light
    - light.opple_cn_831954468_moat_s_2_light

    trigger: state
    from: "off"
    to: "on"
conditions: []
actions:
  - action: light.turn_on
    target:
      entity_id: "{{ trigger.entity_id }}"
    data:
      color_temp_kelvin: "{{ states('var.light_kelvin_' ~ trigger.entity_id[6:]) | int }}"
      brightness_pct: "{{ states('var.light_brightness_' ~ trigger.entity_id[6:]) | int }}"
mode: parallel
