alias: 目标值变化时调整已开启的灯光
description: ""
triggers:
  - trigger: state
    entity_id:
      - var.light_brightness_lemesh_cn_1124092164_wy0c24_s_2_light
      - var.light_kelvin_lemesh_cn_1124092164_wy0c24_s_2_light
      - var.light_brightness_ftd_cn_1119936519_dsplmp_s_2_light
      - var.light_kelvin_ftd_cn_1119936519_dsplmp_s_2_light
      - var.light_brightness_ftd_cn_1120461607_dsplmp_s_2_light
      - var.light_kelvin_ftd_cn_1120461607_dsplmp_s_2_light
      - var.light_brightness_ftd_cn_1120483358_dsplmp_s_2_light
      - var.light_kelvin_ftd_cn_1120483358_dsplmp_s_2_light
      - var.light_brightness_lemesh_cn_1120649848_wy0c24_s_2_light
      - var.light_kelvin_lemesh_cn_1120649848_wy0c24_s_2_light
      - var.light_brightness_lemesh_cn_1120805227_wy0c24_s_2_light
      - var.light_kelvin_lemesh_cn_1120805227_wy0c24_s_2_light
      - var.light_brightness_lemesh_cn_1121166528_wy0c24_s_2_light
      - var.light_kelvin_lemesh_cn_1121166528_wy0c24_s_2_light
      - var.light_brightness_lemesh_cn_1121167017_wy0c24_s_2_light
      - var.light_kelvin_lemesh_cn_1121167017_wy0c24_s_2_light
      - var.light_brightness_lemesh_cn_1121167159_wy0c24_s_2_light
      - var.light_kelvin_lemesh_cn_1121167159_wy0c24_s_2_light
      - var.light_brightness_lemesh_cn_1121168146_wy0c24_s_2_light
      - var.light_kelvin_lemesh_cn_1121168146_wy0c24_s_2_light
      - var.light_brightness_opple_cn_831953828_moat_s_2_light
      - var.light_kelvin_opple_cn_831953828_moat_s_2_light
      - var.light_brightness_opple_cn_845038404_moat_s_2_light
      - var.light_kelvin_opple_cn_845038404_moat_s_2_light
      - var.light_brightness_lemesh_cn_1120498967_wy0c24_s_2_light
      - var.light_kelvin_lemesh_cn_1120498967_wy0c24_s_2_light
      - var.light_brightness_lemesh_cn_1120804999_wy0c24_s_2_light
      - var.light_kelvin_lemesh_cn_1120804999_wy0c24_s_2_light
      - var.light_brightness_lemesh_cn_1121162556_wy0c24_s_2_light
      - var.light_kelvin_lemesh_cn_1121162556_wy0c24_s_2_light
      - var.light_brightness_ftd_cn_1125537084_dsplmp_s_2_light
      - var.light_kelvin_ftd_cn_1125537084_dsplmp_s_2_light
      - var.light_brightness_xiaomi_cn_819688679_lyj3xs_s_3_light
      - var.light_kelvin_xiaomi_cn_819688679_lyj3xs_s_3_light
      - var.light_brightness_xiaomi_cn_819783851_lyj3xs_s_3_light
      - var.light_kelvin_xiaomi_cn_819783851_lyj3xs_s_3_light
      - var.light_brightness_lemesh_cn_1120561054_wy0c24_s_2_light
      - var.light_kelvin_lemesh_cn_1120561054_wy0c24_s_2_light
      - var.light_brightness_lemesh_cn_1121173938_wy0c24_s_2_light
      - var.light_kelvin_lemesh_cn_1121173938_wy0c24_s_2_light
      - var.light_brightness_lemesh_cn_1123300235_wy0c24_s_2_light
      - var.light_kelvin_lemesh_cn_1123300235_wy0c24_s_2_light
      - var.light_brightness_lemesh_cn_1120805171_wy0c24_s_2_light
      - var.light_kelvin_lemesh_cn_1120805171_wy0c24_s_2_light
      - var.light_brightness_opple_cn_845028809_moat_s_2_light
      - var.light_kelvin_opple_cn_845028809_moat_s_2_light
      - var.light_brightness_opple_cn_847058390_moat_s_2_light
      - var.light_kelvin_opple_cn_847058390_moat_s_2_light
      - var.light_brightness_lemesh_cn_1121162570_wy0c24_s_2_light
      - var.light_kelvin_lemesh_cn_1121162570_wy0c24_s_2_light
      - var.light_brightness_lemesh_cn_1121174323_wy0c24_s_2_light
      - var.light_kelvin_lemesh_cn_1121174323_wy0c24_s_2_light
      - var.light_brightness_aupu_cn_822711474_s10m2_s_2_light
      - var.light_kelvin_aupu_cn_822711474_s10m2_s_2_light
      - var.light_brightness_lemesh_cn_1120804698_wy0c24_s_2_light
      - var.light_kelvin_lemesh_cn_1120804698_wy0c24_s_2_light
      - var.light_brightness_lemesh_cn_1120985233_wy0c24_s_2_light
      - var.light_kelvin_lemesh_cn_1120985233_wy0c24_s_2_light
      - var.light_brightness_aupu_cn_822614309_s10m2_s_2_light
      - var.light_kelvin_aupu_cn_822614309_s10m2_s_2_light
      - var.light_brightness_ftd_cn_1119497471_dsplmp_s_2_light
      - var.light_kelvin_ftd_cn_1119497471_dsplmp_s_2_light
      - var.light_brightness_ftd_cn_1120477125_dsplmp_s_2_light
      - var.light_kelvin_ftd_cn_1120477125_dsplmp_s_2_light
      - var.light_brightness_yeelink_cn_112632203_lamp1_s_2_light
      - var.light_kelvin_yeelink_cn_112632203_lamp1_s_2_light
      - var.light_brightness_opple_cn_831954468_moat_s_2_light
      - var.light_kelvin_opple_cn_831954468_moat_s_2_light

    from: null
    to: null
conditions:
  - condition: template
    value_template: >-
      {% set mapped_entity = trigger.entity_id |
      regex_replace('^var\.light_(brightness|kelvin)_', 'light.')  %}
      {{states(mapped_entity) == 'on' }}
actions:
  - if:
      - condition: template
        value_template: "{{trigger.entity_id.startswith('var.light_brightness_')}}"
    then:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_pct: |-
            {% set brightness_entity_id =
             trigger.entity_id|regex_replace('^var\.light_(brightness|kelvin)_','var.light_brightness_')
            %} {{states(brightness_entity_id)|int}}
        target:
          entity_id: >-
            {% set mapped_entity_id =
            trigger.entity_id|regex_replace('^var\.light_(brightness|kelvin)_','light.')
            %} {{mapped_entity_id}}
    else:
      - action: light.turn_on
        metadata: {}
        data:
          color_temp_kelvin: |-
            {% set brightness_entity_id =
              trigger.entity_id|regex_replace('^var\.light_(brightness|kelvin)_','var.light_kelvin_')
             %} {{states(brightness_entity_id)|int}}
        target:
          entity_id: >-
            {% set mapped_entity_id =
            trigger.entity_id|regex_replace('^var\.light_(brightness|kelvin)_','light.')
            %} {{mapped_entity_id}}
mode: parallel
